# Pre-commit Hooks Configuration
#
# These hooks run automatically before each commit to maintain code quality.
# They match the CI configuration exactly to catch issues early.
#
# Setup:
#   1. Install pre-commit: pip install pre-commit (or use pipx)
#   2. Install hooks: pre-commit install
#   3. Run manually: pre-commit run --all-files
#
# The hooks will auto-fix issues when possible, otherwise will fail the commit
# with clear error messages.

repos:
  # Standard file checks (trailing whitespace, file endings, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]

      - id: end-of-file-fixer
        name: Fix end of files
        exclude: '\.svg$'

      - id: check-yaml
        name: Check YAML syntax
        args: [--safe]

      - id: check-json
        name: Check JSON syntax
        exclude: 'tsconfig\.json$'  # tsconfig allows comments

      - id: check-added-large-files
        name: Check for large files
        args: [--maxkb=1000]

      - id: check-merge-conflict
        name: Check for merge conflicts

      - id: check-case-conflict
        name: Check for case conflicts

      - id: mixed-line-ending
        name: Check line endings
        args: [--fix=lf]

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format with Prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]
        exclude: |
          (?x)(
            ^package-lock\.json$|
            ^\.astro/|
            ^dist/|
            ^node_modules/|
            ^coverage/|
            lighthouse-report\.
          )
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-astro@0.12.2

  # ESLint for linting JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        name: Lint with ESLint
        files: \.(js|jsx|ts|tsx|astro)$
        exclude: |
          (?x)(
            ^\.astro/|
            ^dist/|
            ^node_modules/|
            ^coverage/
          )
        args: [--fix, --max-warnings=0]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-plugin-astro@0.31.0
          - '@typescript-eslint/eslint-plugin@6.19.0'
          - '@typescript-eslint/parser@6.19.0'
          - typescript@5.3.3

  # Validate package.json
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-workflows
        name: Validate GitHub Workflows

# Global settings
default_language_version:
  node: '20.0.0'

# Fail fast - stop on first failure
fail_fast: false

# CI settings
ci:
  autofix_commit_msg: 'chore: auto-fix pre-commit hooks'
  autofix_prs: true
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autoupdate_schedule: weekly
